_target_: lightning.Trainer
# profiler: "simple"
default_root_dir: "${paths.log_dir}"
min_epochs: 1
max_epochs: 20
accelerator: 'auto'
devices: 1
# logger: 
#   _target_: lightning.pytorch.loggers.MLFLowLogger
#   experiment_name: "experiment_name"
#   run_name: "run_name"
#   save_dir: "${paths.log_dir}"
# fast_dev_run: True
# strategy: ddp_spawn

