
_target_: lightning.Trainer
# profiler: "simple"
default_root_dir: "${paths.log_dir}"
min_epochs: 1
max_epochs: 2
accelerator: 'auto'
devices: 1
# fast_dev_run: True
# strategy: ddp_spawn
limit_train_batches: 0.008
limit_val_batches: 0.4
limit_test_batches: 1
