
_target_: lightning.Trainer
# profiler: "simple"
default_root_dir: "${paths.log_dir}"
min_epochs: 1
max_epochs: 1
accelerator: 'gpu'
devices: 3
strategy: ddp
limit_train_batches: 0.2
# limit_val_batches: 0.2
# limit_test_batches: 0.2
