# @package _global_

defaults:
  - override /hydra/sweeper: optuna

optimized_metric: "val/mae"
hydra:
  sweep:
    dir: ${paths.output_dir}/multiruns
    subdir: ${hydra.job.override_dirname}
  sweeper:
    sampler:
      seed: 123
    direction: minimize
    storage: null
    study_name: test
    n_trials: 5
    n_jobs: 1
    params:
      pl_module.model.num_layers: choice(1,2,3)
      trainer.max_epochs: choice(2,5,7)


