defaults:
  - _self_
  - datamodule: null
  - runner: null
  - trainer: default.yaml
  - callbacks: default.yaml
  - hydra: default.yaml
  - experiment: null
  - hparams_search: null

seed: 70

# * Paths
paths: 
  base_dir: '.'
  data_dir: "${paths.base_dir}/data"
  output_dir: "${paths.base_dir}/outputs"
  log_dir: "${paths.base_dir}/logs"
  ckpt_dir: "${paths.base_dir}/outputs/checkpoints"
  ckpt_path: "${paths.base_dir}/outputs/checkpoints/last.ckpt"

# * Run mode
run_mode:
  train: true
  test: true
  pred: true
  resume: false
  test_run: false
  hp_search: false

# * Names
memory:
  printout: ${run_mode.test}
  datamodule: datamodule
  runner: runner
  experiment_name: experiment_name
  experiment_sub_name: experiment_sub_name
  run_name: run_name
  run_name_extra: run_name_extra

mlflow:
  tracking_uri: http://192.168.1.100:25001
  experiment_name: experiment_name
  run_name: run_name
  run_description: run_description
  log_datasets: False
  log_models: True

