_target_: src.datamodules.datamodule.DataModule
cfg:
  # * info
  test_run: ${run_mode.test_run}
  data_dir: ${paths.data_dir}
  datafolder_name: base
  dataset_name: custom
  file_name: electricity

  # * args
  size: None
  features: MS
  target: OT
  scale: True
  timeenc: 0
  freq: t
  seasonal_patterns: None
  embed: "timeF"

  # * loader
  batch_size: 64
  num_workers: 1
  
  # * data
  input_dim: 321
  seq_len: 128
  label_len: 12
  pred_len: 24
  past_indices: [24, 48, 72, 168, 336, 720]

  # * test
  run_len: 1000


