_target_: src.datamodules.ts_datamodule.TSDataModule
task_name: pv
data_folder: ${paths.data_dir}
filename: da1_past
selected_cols: null
batch_size: 128
num_workers: 6
pred_idx: 17839
dataset:
  seq_len: 48
  label_len: 12
  pred_len: 24
  target_col: power
  past_len: 24
  past_interval: 3
data_index: null