
_target_: src.pl_modules.pl_former.TSForecastFormer

name: TiDE
optimizer:
  _target_: torch.optim.AdamW
  _partial_: true
  lr: 0.0016
  betas: [0.9, 0.95]
  weight_decay: 0.05
scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.5
  patience: 10
model:
  _target_: src.models.tide.Model
  seq_len: 48
  label_len: 24
  pred_len: 48
  input_size: 11
  past_cov_dim: 7
  temporal_width_past: 3
  future_cov_dim: 7
  temporal_width_future: 3
  hidden_size: 32
  output_dim: 11
  use_layer_norm: True
  dropout: 0.1
  num_encoder_layers: 3
  num_decoder_layers: 3
  decoder_output_dim: 8
  nr_params: 1
  temporal_decoder_hidden: 8


metrics:
  train:
    rmse:
      _target_: torchmetrics.regression.MeanSquaredError
      squared: False
    mae: 
      _target_: torchmetrics.regression.MeanSquaredError
    mape:
      _target_: torchmetrics.regression.MeanAbsolutePercentageError
  val:
    rmse:
      _target_: torchmetrics.regression.MeanSquaredError
      squared: False
    mae: 
      _target_: torchmetrics.regression.MeanSquaredError
    mape:
      _target_: torchmetrics.regression.MeanAbsolutePercentageError
criterion:
  _target_: torch.nn.MSELoss
monitor: val/rmse

pred_len: 48