
_target_: src.pl_modules.pl_former.TSForecastFormer

name: TSMixer
optimizer:
  _target_: torch.optim.AdamW
  _partial_: true
  lr: 0.0016
  betas: [0.9, 0.95]
  weight_decay: 0.05
scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.5
  patience: 10
model:
  _target_: src.models.tsmixer.Model
  seq_len: 48
  label_len: 24
  pred_len: 48
  input_size: 18
  hidden_size: 32
  dropout: 0.1
  n_block: 3


  
metrics:
  train:
    rmse:
      _target_: torchmetrics.regression.MeanSquaredError
      squared: False
    mae: 
      _target_: torchmetrics.regression.MeanSquaredError
    mape:
      _target_: torchmetrics.regression.MeanAbsolutePercentageError
  val:
    rmse:
      _target_: torchmetrics.regression.MeanSquaredError
      squared: False
    mae: 
      _target_: torchmetrics.regression.MeanSquaredError
    mape:
      _target_: torchmetrics.regression.MeanAbsolutePercentageError
criterion:
  _target_: torch.nn.MSELoss
monitor: val/rmse

pred_len: 48